name = "air-quality-app-prod"
main = "./dist/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat", "websocket_outbound"]

account_id = "fe1b6d9276e7ce4ea4d7f12073d9fbbe"


[build]
command = "bun build ./src/index.ts --outfile ./dist/index.js --target node --format esm"

[[routes]]
pattern = "air-quality.everywoah.com/*"
zone_name = "everywoah.com"